### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by joel-simon** [mikessh/migmap#31]
Command:

```
MIGMAP="java -Xmx50G -jar /home/registry5/apps/migmap-0.9.9/migmap-0.9.9.jar"
$MIGMAP -R IGH -S human -q 25 --allow-noncanonical --allow-incomplete  in.fastq out.migmap.tsv

```

Error Stack:

```
Exception in thread "Thread-63" java.lang.StringIndexOutOfBoundsException: String index out of range: 39
    at java.lang.String.charAt(String.java:658)
    at com.antigenomics.migmap.blast.PSegmentSearcher.searchLeft(PSegmentSearcher.groovy:80)
    at com.antigenomics.migmap.blast.PSegmentSearcher.search(PSegmentSearcher.groovy:37)
    at com.antigenomics.migmap.blast.PSegmentSearcher$search.call(Unknown Source)
    at com.antigenomics.migmap.blast.BlastInstance.createReadMapping(BlastInstance.groovy:124)
    at com.antigenomics.migmap.blast.BlastInstance.take(BlastInstance.groovy:199)
    at com.antigenomics.migmap.Pipeline$2.run(Pipeline.groovy:84)
    at java.lang.Thread.run(Thread.java:745)

```

It then gets stuck in  loop repeating the same output. 

Attached is a fastq file that produces the output. The reads are CDR3 region only, with a min nt length of 40.  Help is very much appreciated as im getting this with several files. 

Thanks a lot,
Joel

[290test.fastq.zip](https://github.com/mikessh/migmap/files/157885/290test.fastq.zip)

**Comment by mikessh** [comment]
Dear Joel,

I think I've already fixed it in develop branch with 49ab794eba35b574a4d8fdb6920d0d292ff454dc

You can try to compile the latest develop commit, or wait till the next release (in case it is very urgent I can compile it for you and attach here).

Best,
Mike

**Comment by joel-simon** [comment]
Hi Mike,

Thank you for your fast response!
Attaching the build here would be fantastic and much appreciated.

Thanks,
Joel

**Comment by mikessh** [comment]
Here you go!
You just need to replace the old jar file with the new one [here](https://github.com/mikessh/migmap/files/159504/migmap-1.0.0-SNAPSHOT.zip).

The main reason for this bug is that IgBlast frequently reports D hits that overlap J region.

Frankly speaking, this (49ab794eba35b574a4d8fdb6920d0d292ff454dc) is not the best workaround, as it can miss some short D segment hits in case they are moved down the list as IgBlast finds long D hits overlapping with J region.

**Comment by joel-simon** [comment]
Thank you very much!

What are the practical consequences of that shortcoming? Will some D, J genes or CDR3 be misclassified?

**Comment by mikessh** [comment]
Some moderate D segment alignments will not be reported in case a good D alignment that overlaps J segment was found. I'll try to fix it in later versions

**Comment by anoronh4** [comment]
I am getting a similar error with migmap-1.0.2, which was released well after the closing of this thread. Here's the error:
```
Exception in thread "Thread-14" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at com.antigenomics.migmap.blast.PSegmentSearcher.searchLeft(PSegmentSearcher.groovy:80)
	at com.antigenomics.migmap.blast.PSegmentSearcher.search(PSegmentSearcher.groovy:37)
	at com.antigenomics.migmap.blast.PSegmentSearcher$search.call(Unknown Source)
	at com.antigenomics.migmap.blast.BlastInstance.createReadMapping(BlastInstance.groovy:128)
	at com.antigenomics.migmap.blast.BlastInstance.take(BlastInstance.groovy:209)
	at com.antigenomics.migmap.pipeline.Pipeline$2.run(Pipeline.groovy:84)
	at java.lang.Thread.run(Thread.java:748)

```
This is error is reproducible. In all honesty I don't think this is an ideal dataset. We tried something new so we're not sure if it worked. Even so, this error tells us nothing. My command is:

`/path/to/migmap-1.0.2/migmap --data-dir /path/to/directory --blast-dir /path/to/migmap-1.0.2/ncbi-igblast-1.7.0/bin -p 8 -R TRB,TRD -S human --details fr1nt,cdr1nt,fr2nt,cdr2nt,fr3nt,fr4nt,contignt,fr1aa,cdr1aa,fr2aa,cdr2aa,fr3aa,fr4aa,contigaa /path/to/sample.contig.fasta  sample_clones.migmap.xls  `

Some samples in this dataset worked, others did not. 

Any help you can offer is greatly appreciated!
